In [2]:
import pandas as pd 
import numpy as np 

In [3]:
import tensorflow 
from tensorflow import keras 
from tensorflow.keras import Sequential
from keras.layers import Dense

In [4]:
from sklearn.datasets import make_moons

In [5]:
x,y = make_moons(n_samples=1000,noise=0.2,random_state=1)

In [8]:
import matplotlib.pyplot as plt

In [9]:
model = Sequential()

model.add(Dense(10,activation='relu',input_dim=2,kernel_initializer='he_normal'))
model.add(Dense(10,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(10,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(10,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

d:\python\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 371 (1.45 KB)

 Trainable params: 371 (1.45 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.get_weights()

[array([[-2.2087784 , -1.1663187 ,  0.9062035 ,  1.7558537 ,  0.22032206,
         -0.6037925 , -0.37437707, -0.43964532,  1.0872902 , -0.61933637],
        [-0.4440666 ,  0.6481139 , -1.0773691 , -0.0056747 ,  0.6034438 ,
         -1.5791464 ,  0.80059946,  0.3652306 , -1.5672791 ,  0.9443207 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.2942383 ,  0.256422  ,  0.18718685,  0.5305223 , -0.14370047,
          0.5891626 , -0.06163048, -0.3074155 ,  0.32264286, -0.2821314 ],
        [-0.40179384, -0.5367217 , -0.83025193, -0.30349854, -0.1252985 ,
         -0.14073491, -0.49484342, -0.5154164 ,  0.4034031 , -0.3662385 ],
        [-0.08006775, -0.24172518, -0.21959668, -0.467374  , -0.08292491,
          0.7356015 , -0.10815257, -0.55808026,  0.14669953, -0.3001581 ],
        [ 0.08801114, -0.23580651, -0.5588556 ,  0.39970943, -0.5878775 ,
          0.6234889 , -0.30239743, -0.5750118 , -0.41262102,  0.14534621],
        [ 0.27048

In [11]:
initial_weights = model.get_weights()

In [12]:
initial_weights[0] = np.random.randn(2,10)*np.sqrt(1/2)
initial_weights[1] = np.zeros(model.get_weights()[1].shape)
initial_weights[2] = np.random.randn(10,10)*np.sqrt(1/10)
initial_weights[3] = np.zeros(model.get_weights()[3].shape)
initial_weights[4] = np.random.randn(10,10)*np.sqrt(1/10)
initial_weights[5] = np.zeros(model.get_weights()[5].shape)
initial_weights[6] = np.random.randn(10,10)*np.sqrt(1/10)
initial_weights[7] = np.zeros(model.get_weights()[7].shape)
initial_weights[8] = np.random.randn(10,1)*np.sqrt(1/10)
initial_weights[9] = np.zeros(model.get_weights()[9].shape)

In [13]:
model.set_weights(initial_weights)

In [14]:
model.get_weights()

[array([[ 0.34048823,  0.5059627 ,  0.13146998,  1.0265312 , -1.4004725 ,
          0.4909398 , -0.91181827, -0.504488  , -0.14488629, -0.02194802],
        [ 1.3369979 ,  0.37393   ,  0.05810617, -0.6977621 , -0.27512643,
         -0.27828223,  0.8929842 ,  0.24699588,  0.6373883 ,  0.21049589]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.15828875,  0.08814102, -0.34980872,  0.5272808 , -0.0096075 ,
         -0.17149103, -0.15401554,  0.28075215,  0.06521475, -0.08742715],
        [ 0.18210164,  0.11927629,  0.36203116,  0.11805084,  0.19362351,
          0.47372752, -0.5642144 , -0.08339018, -0.69395536, -0.20808472],
        [ 0.08864739, -0.08398373, -0.00441445,  0.5487546 , -0.3679137 ,
         -0.03639401,  0.6270438 ,  0.1509915 ,  0.03994399,  0.1296054 ],
        [ 0.03279491, -0.09858412, -0.41381043,  0.01243008, -0.15826024,
         -0.05162259, -0.21823566, -0.47271585, -0.15598153, -0.05974094],
        [ 0.11715

In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
history = model.fit(x,y,epochs=100,validation_split=0.2)

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - accuracy: 0.5482 - loss: 0.6952 - val_accuracy: 0.8100 - val_loss: 0.6768
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8229 - loss: 0.6704 - val_accuracy: 0.8350 - val_loss: 0.6487
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8496 - loss: 0.6406 - val_accuracy: 0.8350 - val_loss: 0.6031
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8482 - loss: 0.5889 - val_accuracy: 0.8250 - val_loss: 0.5433
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8463 - loss: 0.5402 - val_accuracy: 0.8350 - val_loss: 0.4866
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8440 - loss: 0.4810 - val_accuracy: 0.8450 - val_loss: 0.4364
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8339 - loss: 0.4408 - val_accuracy: 0.8400 - val_loss: 0.3915
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8163 - loss: 0.4255 - val_accuracy: 0.8600 - 

In [17]:
model.get_weights()

[array([[ 0.9744453 ,  0.68926275,  0.15432987,  1.2074085 , -1.8831395 ,
          0.90375614, -1.1861011 , -0.9155517 , -0.18290506, -0.2085146 ],
        [ 1.3882881 ,  0.46769065, -0.18598646, -0.6786777 , -0.32657585,
         -0.5404091 ,  0.9835646 ,  0.25745228,  0.457629  , -0.06515709]],
       dtype=float32),
 array([-0.05970846, -0.04680719,  0.62504625, -0.6165183 , -0.2153892 ,
         0.16436517, -0.18830045, -0.19434932,  0.50750387,  0.5138724 ],
       dtype=float32),
 array([[-0.16738608,  0.16542694, -0.23844315,  0.701419  , -0.09587579,
         -0.07941183, -0.30776054,  0.38282266,  0.05624122, -0.37539333],
        [ 0.17016336,  0.17537497,  0.4746236 ,  0.42933774,  0.11058582,
          0.4993883 , -0.8961388 ,  0.02895662, -0.69138527, -0.6168942 ],
        [ 0.07305803,  0.11172441,  0.26779917,  0.8798536 , -0.42518145,
          0.09773391,  0.7744608 ,  0.38341382,  0.0363467 ,  0.4577959 ],
        [ 0.02062728, -0.37863916, -0.7280568 ,  0.5793131 , 

In [19]:
(np.random.randn(10,10)*0.01).min()

-0.02690605999729848

In [20]:
(np.random.randn(10,10)*0.01).max()

0.024376055821990955